services:
  beerbot:
    build:
      context: .
      network: host
    secrets:
      - config.toml
    volumes:
      - "/etc/localtime:/etc/localtime:ro"

secrets:
  config.toml:
    file: ./config.toml
